### ISSUE TITLE
add autoload capability

### ISSUE THREAD

**Issue by bradrydzewski** [jackspirou/syscerts#1]
I'll send a pull request for this, but just wanted to get this documented so I don't forget. I was thinking would could add an auto-load package that would load the syscerts into the default transport's tls config. So something like this:

``` Go
package autoload

func init() {
  http.DefaultTransport = &http.Transport{
    Proxy: ProxyFromEnvironment,
    Dial: (&net.Dialer{
      Timeout:   30 * time.Second,
      KeepAlive: 30 * time.Second,
    }).Dial,
    TLSHandshakeTimeout:   10 * time.Second,
    ExpectContinueTimeout: 1 * time.Second,
    TLSClientConfig: &tls.Config{ RootCAs: syscerts.SystemRootsPool() },
  }
}
```

which could then be imported like this:

```
import (
   _ "github.com/jackspirou/syscerts/autoload"
)
```

**Comment by jackspirou** [comment]
@bradrydzewski great idea.  I added the `autoload` package.
